;;; julia-ts-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from julia-ts-mode.el

(add-to-list 'auto-mode-alist '("\\.jl\\'" . julia-ts-mode))
(autoload 'julia-ts-mode "julia-ts-mode" "\
Major mode for Julia files using tree-sitter.

(fn)" t)
(register-definition-prefixes "julia-ts-mode" '("julia-ts-"))

;;; End of scraped data

(provide 'julia-ts-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; julia-ts-mode-autoloads.el ends here
